### ISSUE TITLE
🐛 [Bug] isBool() INTERNAL ASSERT FAILED while compiling Sequence Generator

### ISSUE THREAD

**Issue by Csinclair0** [pytorch/TensorRT#1697]
##  Bug Description
I am receving this  error when compling a torchscript module. The module is a light wrapper around a [SequenceGenerator](https://github.com/facebookresearch/fairseq/blob/main/fairseq/sequence_generator.py) from fairseq. 
```
RuntimeError: isBool() INTERNAL ASSERT FAILED at "bazel-out/k8-opt/bin/external/libtorch_pre_cxx11_abi/_virtual_includes/ATen/ATen/core/ivalue.h":625, please report a bug to PyTorch. 
```
## To Reproduce

I am currently executing sequence generation in torch, using the compile spec. 
```
trt_ts_module = torch_tensorrt.ts.compile(generator,
  inputs=[    
          torch_tensorrt.Input(min_shape=(1,4), opt_shape = (1,10), max_shape = (1,20) , dtype = torch.int32),  
      ],   
      debug= True, 
      enabled_precisions={torch.half},    
      truncate_long_and_double=True,
      require_full_compilation=False, 
      torch_executed_modules= ["fairseq.sequence_generator.SequenceGenerator"], 
      min_block_size = 1
  )
```

## Expected behavior

no compile errors 

## Environment

building docker image from Dockerfile in repo.

**Comment by narendasan** [comment]
Can you share the logs from the failure?

**Comment by Csinclair0** [comment]
Here is the [full_logs](https://github.com/pytorch/TensorRT/files/10841941/logs_trt_debug.txt)

**Comment by narendasan** [comment]
Looking at the logs, it seems like this error pops up during graph splitting. @bowang007 Can you take a look or delegate this to someone?

**Comment by peri044** [comment]
```
RuntimeError: isBool() INTERNAL ASSERT FAILED at "bazel-out/k8-opt/bin/external/libtorch_pre_cxx11_abi/_virtual_includes/ATen/ATen/core/ivalue.h":625, please report a bug to PyTorch. 
```
Looks like we some converter args failure. @bowang007  Can you take a look at this ?

**Comment by bowang007** [comment]
sure. Let me check what's going on

**Comment by bowang007** [comment]
Hey @Csinclair0 This bug was fixed by this PR: https://github.com/pytorch/TensorRT/pull/1691
This PR was merged into our master branch last week, please take a took and try if it works. 
Thanks!

**Comment by Csinclair0** [comment]
Thanks for looking into it! I am unfortunately still seeing the same error. 
[logs](https://github.com/pytorch/TensorRT/files/11093072/logs.txt)

**Comment by bowang007** [comment]
can you try fx btw? @Csinclair0

**Comment by Csinclair0** [comment]
I am running into other issues using fx with unsupported operators, will look more modifying the code to potentially support it. 
```TypeError: int() argument must be a string, a bytes-like object or a number, not 'Proxy'```

 Regarding your install issue, the solution [here](https://github.com/facebookresearch/fairseq/issues/2908) seems to be to update pip.

**Comment by bowang007** [comment]
@Csinclair0 I'm now trying to reproduce your error in our latest container but I have this error: 
```
RuntimeError: 
undefined value torch:
  File "/root/.pyenv/versions/3.10.11/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 92
            if length > max_length: max_length = length
            if source_length > max_source: max_source = source_length        
        output_tokens = torch.zeros(bsz, beam_size, max_length, dtype = torch.int32, device = device)
                        ~~~~~ <--- HERE
        for output in range(bsz):
            for idx in range(beam_size):
```
I spent some time for this but didn't find anything useful. I think this is because of torch, we are now having torch 2.0 for our latest torch-tensorrt container. Have you run into this issue? 
Thanks!

**Comment by Csinclair0** [comment]
Yes, that is indeed due to the torch 2.0 upgrade. A solution I've found that works for me is to remove the @torch.no_grad decorator from the forward method in TritonGenerator.

**Comment by gs-olive** [comment]
Hi @Csinclair0 - as an update on this issue, there were some recent fixes for conditional logic in TorchScript, including #1933 and #1859, which may help with this bug. I have created a branch [`uninitialized_fix_rebased`](https://github.com/pytorch/TensorRT/tree/uninitialized_fix_rebased), which has those code changes reflected on the latest `main`. Could you try compiling the model with a Docker container built from that branch?

**Comment by gs-olive** [comment]
I investigated this issue further in the Torch-TensorRT Dynamo path and have a few updates to share:

## Initial Investigation of Tracing `generator` in FX
To investigate FX tracing of the generator object, I used the `torch._dynamo.explain` API. Here are the highlights:
```python
explanation = torch._dynamo.explain(generator)(input_tensor)
```
- 31 graph breaks are generated. They are primarily caused by conditional (`if`) statement logic which is not traceable.
  - `torch.jit.annotate`: [Code Link](https://github.com/Csinclair0/fairseq/blob/67d69732e3780f82d971ca4157816472bc3e1419/fairseq/sequence_generator.py#L196-L202)
  - `if` 1: [Code Link](https://github.com/Csinclair0/fairseq/blob/67d69732e3780f82d971ca4157816472bc3e1419/fairseq/models/transformer.py#L934-L935)
  - `if` 2: [Code Link](https://github.com/Csinclair0/fairseq/blob/67d69732e3780f82d971ca4157816472bc3e1419/fairseq/models/transformer.py#L517-L518)

**Note:** These graph breaks are automatically handled in `torch.compile`, but they make it difficult to serialize the model, currently.

## Methods
For this model, I directly compiled the graph with the `torch.compile` API, as follows:

```python
import torch
import torch_tensorrt


trt_dynamo_module = torch.compile(generator,
                                  backend="torch_tensorrt",
                                  dynamic=False,
                                  options={
                                      "debug": True,
                                      "enabled_precisions": {torch.float, torch.half},
                                      "truncate_long_and_double": True,
                                      "min_block_size": 25,
                                      }
                                    )
output_trt = trt_dynamo_module(input_tensor)
```

The above succeeds, and has the following missing operators:
```python
- torch.ops.aten.ne.Scalar
- torch.ops.aten.bitwise_and.Tensor
- torch.ops.aten.any.default 
- torch.ops.aten.cumsum.default
- torch.ops.aten._scaled_dot_product_flash_attention.default
- torch.ops.aten.index.Tensor
- torch.ops.aten.bmm.default
- torch.ops.aten.topk.default
```
## Summary and Next Steps
The Torch-TensorRT `torch.compile` backend is a functional approach to compile this model in a JIT-style, however we cannot currently serialize this model in FX in its current form, given the graph breaks. If we were to modify the code to remove these clauses which result in such breaks, we could potentially get it to a state where the graph can be serialized and exported with our `torch_tensorrt.compile(generator, ir="dynamo")` API. I am continuing to investigate model code modifications to enable this, and will follow up on this issue with any further findings on this, as the `ir="dynamo"` path evolves.
